# Generated by Django 3.2.4 on 2021-11-07 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_date', models.DateField(blank=True, null=True)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, validators=[django.core.validators.MaxLengthValidator(13)])),
                ('landline', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('mfname', models.CharField(blank=True, max_length=100, null=True)),
                ('mlname', models.CharField(blank=True, max_length=100, null=True)),
                ('mcontact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('memail', models.EmailField(blank=True, max_length=254, null=True)),
                ('ffname', models.CharField(blank=True, max_length=100, null=True)),
                ('flname', models.CharField(blank=True, max_length=100, null=True)),
                ('fcontact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('femail', models.EmailField(blank=True, max_length=254, null=True)),
                ('c1full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation1', models.CharField(blank=True, max_length=100, null=True)),
                ('c1contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('c2full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation2', models.CharField(blank=True, max_length=100, null=True)),
                ('c2contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcg_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hepb1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hepb2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('dt1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ip1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hi1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('pcv1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rota1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('dt2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ip2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hi2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('pcv2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rota2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hepb3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('dt3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ip3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hi3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('pcv3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rota3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('influ1of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('measles_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('jap1of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('influ2of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mmr1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('vari1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('dtbooster1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ipbooster1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hibooster1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('pcvbooster1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('inacthepa1_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('inacthepa2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mening_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('typhoid_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('jap2of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('dtbooster2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ipbooster2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mmr2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('vari2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('tdbooster3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hpv1of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hpv2of2_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hpv1of3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hpv2of3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hpv3of3_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('bcg_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docpatient', to='tracker.physician'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Blank', 'Blank'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Requested', 'Requested')], max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('visit', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.physician')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient')),
            ],
        ),
    ]
