# Generated by Django 3.2.4 on 2021-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20211108_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
