# Generated by Django 3.2.4 on 2021-11-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_patient_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bcg_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dt1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dt2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dt3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dtbooster1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dtbooster2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hepb1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hepb2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hepb3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hi1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hi2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hi3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hibooster1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv1of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv1of3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv2of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv2of3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hpv3of3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inacthepa1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inacthepa2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='influ1of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='influ2of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ip1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ip2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ip3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ipbooster1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ipbooster2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='jap1of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='jap2of2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measles_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mening_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mmr1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mmr2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pcv1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pcv2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pcv3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pcvbooster1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rota1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rota2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rota3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tdbooster3_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='typhoid_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vari1_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vari2_loc',
            field=models.CharField(blank=True, choices=[('R Thigh', 'R Thigh'), ('L Thigh', 'L Thigh'), ('R Arm', 'R Arm'), ('L Arm', 'L Arm'), ('R Buttocks', 'R Buttocks'), ('L Buttocks', 'L Buttocks')], max_length=100, null=True),
        ),
    ]
