# Generated by Django 3.2.4 on 2021-11-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20211108_1424'),
        ('tracker', '0032_patient_cert_date'),
    ]

    operations = [
    ]
