# Generated by Django 3.1.7 on 2021-12-01 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_remove_vaccine_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient'),
        ),
    ]
