# Generated by Django 3.1.7 on 2021-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0054_auto_20211203_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='age',
            field=models.CharField(choices=[('Birth', 'Birth'), ('2 to 3 months', '2 to 3 months'), ('4 to 5 months', '4 to 5 months'), ('6 to 7 months', '6 to 7 months'), ('9 months', '9 months'), ('12 to 15 months', '12 to 15 months'), ('18 to 21 months', '18 to 21 months'), ('24 months', '24 months'), ('4 to 6 yrs ', '4 to 6 yrs '), ('10 yrs', '10 yrs'), ('9-14 yrs', '9-14 yrs'), ('15 and up', '15 and up'), ('Annual', 'Annual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dose',
            field=models.CharField(choices=[('1 of 1', '1 of 1'), ('1 of 2', '1 of 2'), ('1 of 3', '1 of 3'), ('1 of 4', '1 of 4'), ('1 of 5', '1 of 5'), ('2 of 2', '2 of 2'), (' 2 of 3', '2 of 3'), ('2 of 4', '2 of 4'), ('2 of 5', '2 of 5'), ('3 of 3', '3 of 3'), ('3 of 4', '3 of 4'), ('3 of 5', '3 of 5'), ('4 of 4', '4 of 4'), ('4 of 5', '4 of 5'), ('5 of 5', '5 of 5'), ('every 10 years', 'every 10 years')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis B #1', 'Hepatitis B #1'), ('Hepatitis B #2', 'Hepatitis B #2'), ('DTaP/DTwP #1', 'DTaP/DTwP #1'), ('IPV/OPV #1', 'IPV/OPV #1'), ('HiB #1', 'HiB #1'), ('PCV #1', 'PCV #1'), ('Rotavirus #1', 'Rotavirus #1'), ('DTaP/DTwP #2', 'DTaP/DTwP #2'), ('IPV/OPV #2', 'IPV/OPV #2'), ('HiB #2', 'HiB #2'), ('PCV #2', 'PCV #2'), ('Rotavirus #2', 'Rotavirus #2'), ('Hepatitis B #3', 'Hepatitis B #3'), ('DTaP/DTwP #3', 'DTaP/DTwP #3'), ('IPV/OPV #3', 'IPV/OPV #3'), ('HiB #3', 'HiB #3'), ('PCV #3', 'PCV #3'), ('Rotavirus #3', 'Rotavirus #3'), ('Influenza #1', 'Influenza #1'), ('Measles', 'Measles'), ('Japanese Encephalitis B #1', 'Japanese Encephalitis B #1'), ('Influenza #1', 'Influenza #1'), ('MMR #1', 'MMR #1'), ('Varicella #1', 'Varicella #1'), ('DTaP/DTwP Booster #1', 'DTaP/DTwP Booster #1'), ('IPV/OPV Booster #1', 'IPV/OPV Booster #1'), ('HiB Booster #1', 'HiB Booster #1'), ('PCV Booster #1', 'PCV Booster #1'), ('Inactivated Hepatitis A #1', 'Inactivated Hepatitis A #1'), ('Inactivated Hepatitis A #2', 'Inactivated Hepatitis A #2'), ('Meninggococcal vaccine', 'Meninggococcal vaccine'), ('Typhoid', 'Typhoid'), ('Japanese Encephalitis B #2', 'Japanese Encephalitis B #2'), ('DTaP/DTwP Booster #2', 'DTaP/DTwP Booster #2'), ('IPV/OPV Booster #2', 'IPV/OPV Booster #2'), ('MMR #2', 'MMR #2'), ('Varicella #2', 'Varicella #2'), ('Td/Tdap Booster #3', 'Td/Tdap Booster #3'), ('HPV #1', 'HPV #1'), ('HPV #2', 'HPV #2'), ('HPV #1', 'HPV #1'), ('HPV #2', 'HPV #2'), ('HPV #3', 'HPV #3'), ('Influenza', 'Influenza')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PatientVaccine',
        ),
    ]
