# Generated by Django 3.1.7 on 2021-12-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0057_auto_20211203_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
