# Generated by Django 3.2.4 on 2022-01-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20211119_0250'),
        ('tracker', '0058_vaccine_due_date'),
    ]

    operations = [
    ]
